name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run linter
      - name: Analyze code
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test
